//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.17 at 03:28:32 PM MDT 
//


package com.advanced.xml;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stockQuote" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="price" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stockQuote"
})
@XmlRootElement(name = "stocks")
public class Stocks implements XMLDomainObject {

    @XmlElement(name = "stockQuote")
    protected List<Stocks.StockQuote> stockQuote;

    /**
     * Gets the value of the stockQuote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stockQuote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStockQuote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stocks.StockQuote }
     * 
     * 
     */
    public List<Stocks.StockQuote> getStockQuote() {
        if (stockQuote == null) {
            stockQuote = new ArrayList<Stocks.StockQuote>();
        }
        return this.stockQuote;
    }
    
    public String toString() {
    	
    	String stockIndex = null;
    	String stockList = "stock_info{";
    	stockQuote = getStockQuote();
    	
    	for (int i = 0; i < stockQuote.size(); i++) {
    		stockIndex = "stock{" +
                "symbol='" + stockQuote.get(i).getSymbol().toString() + '\'' +
                ", price='" + stockQuote.get(i).getPrice().toString() + '\'' +
                ", time='" + stockQuote.get(i).getTime().getTime().toString() + '\'' +
                '}';
    		stockList = stockList.concat(stockIndex);
    	}
    	stockList = stockList.concat("}");
    	return stockList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="price" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    @Entity
    @Table(name="quotes", catalog = "stocks")
    public static class StockQuote {

        @XmlValue
        protected String value;
        
        @XmlAttribute(name = "symbol")
        protected String symbol;
        @XmlAttribute(name = "price")
        protected String price;
        @XmlAttribute(name = "time")
        protected String time;
        
        /** Primary key */
        @XmlAttribute(name = "id")
        protected int id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        @Id
        @Column(name = "id", nullable = false)
        public int getId() {
            return id;
        }

        
        //  The following are the data attributes from the original StockQuote class
        
        /**
         * Gets the value of the symbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Column(name = "symbol", nullable = false, length = 4)
        public String getSymbol() {
            return symbol;
        }

    	/**
    	 * The setters look like regular set methods for a data model
    	 * 
    	 */
    	
        public void setId(int p_id) {
            this.id = p_id;
        }
        
        /**
         * Sets the value of the symbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Column(name = "price", nullable = false)
        public Double getPrice() {
            return Double.parseDouble(price);
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrice(String value) {
            this.price = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Column(name = "time", nullable = false)
        public Calendar getTime() {
        	SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        	Calendar dd = Calendar.getInstance();
			try {
				dd.setTime(dateFormat.parse(time));
			} catch (ParseException e) {
				e.printStackTrace();
			}
        	return dd;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }     
    }
}